name: Generate pacman Animation

on:
  schedule:
    - cron: '0 */5 * * *'  # Every 12 hours at minute 0
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ergit24

      - name: Debug file existence
        run: |
          ls -la
          if [ -f pacman-contribution-graph.svg ]; then
            echo "File exists"
          else
            echo "Error: pacman-contribution-graph.svg not found"
            exit 1
          fi

      - name: Setup output folder
        run: |
          mkdir -p dist
          if [ -f pacman-contribution-graph.svg ]; then
            mv pacman-contribution-graph.svg dist/
          else
            echo "Error: pacman-contribution-graph.svg not found"
            exit 1
          fi

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
